# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format
  entry: hooks/terraform-fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files
  entry: hooks/terraform-validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: tflint
  name: tflint
  description: Linter for Terraform source code
  entry: hooks/tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: terragrunt-fmt
  name: Terragrunt fmt
  description: Rewrites all Terragrunt configuration files to a canonical format
  entry: hooks/terragrunt-hclfmt.sh
  language: script
  files: \.hcl
  exclude: \.+.terragrunt-cache\/.*$

- id: terragrunt-validate
  name: Terragrunt validate
  description: Validates all Terragrunt configuration files
  entry: hooks/terragrunt-validate.sh
  language: script
  files: \.hcl$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: shellcheck
  name: Shellcheck Bash Linter
  description: Performs linting on bash scripts
  entry: hooks/shellcheck.sh
  language: script

- id: dockerfiles
  name: Hadolint runner
  description: Runs Hadolint fo check for Dockerfile best practices
  entry: hadolint/hadolint hadolint
  language: docker_image
  files: Dockerfile.*$

